background_opacity 0.85
tab_bar_edge top
tab_bar_style fade
tab_bar_min_tabs 1
tab_bar_margin_height 0.0
tab_bar_margin_width 0.0

allow_remote_control yes
clipboard_control write-clipboard read-clipboard

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

enable_audio_bell no
kitty_mod ctrl+shift
keyboard_mode normal

map kitty_mod+escape disable_ligatures_in active always
enable_key_encoding no

macos_option_as_alt yes
macos_titlebar_color background
macos_window_background_blur 20

hide_window_decorations titlebar-only

