gui:
  useHunkModeInStagingView: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse
  showIcons: true
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

keybinding:
  universal:
    quit: "q"
    return: "<esc>"

confirmOnQuit: false

