tool = fzf
flags = --nth=1 --reverse +s --inline-info --height 35% --no-mouse
includes = ~/.config/h_command/zc_config.toml

# EDIT
[000-edit-config]
command = $EDITOR ~/.config/h_command/config.toml

[edit-i3config]
command = $EDITOR ~/.config/i3/config

[edit-tmux]
command = $EDITOR ~/.config/tmux/tmux.conf

[edit-shell_config]
command = $EDITOR ~/.local/share/jover/shell_config.sh

[edit-sshproxy]
command = $EDITOR ~/.local/bin/sshproxy

[edit-test]
command = echo $(?word1:word1) $(?word2) $(?word3:word3)


# GIT
[git-proxy-on]
command = git config --global http.proxy "http://localhost:8889" && git config --global https.proxy "http://localhost:8889"

[git-proxy-off]
command = git config --global --unset http.proxy && git config --global --unset https.proxy


# NET
[net-check-port(lsof)]
command = sudo lsof -i :$(?port)

[net-host-ip]
command = hostname --all-ip-addresses | tr " " "\n" | grep -v "0.0.0.0" | grep -v "127.0.0.1"
command/darwin = ifconfig  | grep -E 'inet.[0-9]' | grep -v '127.0.0.1' | awk '{ print $2}'

[net-start-http]
command = python3 -m http.server $(?port)

[net-whois-domain]
command = /usr/bin/whois -h whois.internic.net $(?domain) | sed '/NOTICE:/q'

[net-iptables-redsocks-create-31338]
command = sudo iptables -t nat -N REDSOCKS; sudo iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN; sudo iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN; sudo iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 31338

[net-iptables-redsocks-delete]
command = sudo iptables -t nat -F REDSOCKS; sudo iptables -t nat -X REDSOCKS

[net-iptables-redsocks-show]
command = sudo iptables -t nat -L REDSOCKS -n -v

[net-iptables-redsocks-apply-for-docker]
command = sudo iptables -t nat -A PREROUTING -i $(?driver:docker0) -p tcp -j REDSOCKS

[net-iptables-redsocks-delete-for-docker]
command = sudo iptables -t nat -D PREROUTING -i $(?driver:docker0) -p tcp -j REDSOCKS

[net-iptables-redsocks-show-all-preroutings]
command = sudo iptables -t nat -L PREROUTING -n -v

# DOC
[doc-git]
command = cat $WS/sourcecode/github/awesome-cheatsheets/tools/git.txt | fzf --reverse

[doc-gdb]
command = cat $WS/sourcecode/github/awesome-cheatsheets/tools/gdb.txt | fzf --reverse


# SSH
[ssh-proxy-start]
command = sshproxy start

[ssh-proxy-ps]
command = sshproxy ps

[ssh-proxy-stop]
command = sshproxy stop

[ssh-self]
command = ssh 127.0.0.1


# System
[system-proxy-enable]
command = export HTTP_PROXY=http://127.0.0.1:8889 && export HTTPS_PROXY=http://127.0.0.1:8889

[system-proxy-disable]
command = unset HTTP_PROXY && unset HTTPS_PROXY

[system-swapshow]
command = swapon --show

[system-swapon]
command = sudo swapon ~/.local/swaps/swapfile

[system-swapoff]
command = sudo swapoff ~/.local/swaps/swapfile

[system-swapon-2]
command = sudo swapon ~/.local/swaps/swapfile2

[system-swapoff-2]
command = sudo swapoff ~/.local/swaps/swapfile2

[system-docker-start]
command = sudo systemctl start docker.service

[system-docker-stop]
command = sudo systemctl stop docker.socket && sudo systemctl stop docker.service

# MISC
[misc-supervisor-reload]
command = sudo supervisorctl reload

[misc-weather]
command = curl -s wttr.in/?n0

[misc-benchmark-cpu]
command = python3 -c "import test.pystone;print(test.pystone.pystones(500000))"

[misc-benchmark-mem]
command = dd if=/dev/zero of=/dev/null bs=1M count=32768

[misc-disk-usage]
command = df -h

[misc-system-info]
command = neofetch

[misc-create-qr-code]
command = echo '$(?content)' | curl -F-=\<- qrenco.de

[misc-yay-downgrading-package]
command = yay -U $(?see /var/cache/pacman/pkg)

[misc-history]
;command = $(omz_history | awk '{$1=""}1' | awk '!seen[$0]++' | fzf --nth 1 --inline-info)
command = cat ~/.zsh_history | fzf --nth 1..2 --inline-info +s --reverse --tac --height 35%

[misc-i3-xprop]
command = xprop

[misc-grep]
command = rg -n --no-heading "$(?word)" "$(?path:$PWD)"

[misc-weather]
command = curl v2.wttr.in/Guangzhou

# Device
[device-cpu-frequency-show]
command = cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq

[device-cpu-frequency-saving-mode]
command = sudo cpupower frequency-set -u 1.6GHz

[device-cpu-frequency-unlimited-mode]
command = sudo cpupower frequency-set -u 3.2GHz

[device-keyboard-laptop]
command = setxkbmap -option && setxkbmap -option ctrl:swapcaps

[device-keyboard-normal]
command = setxkbmap -option

[device-keyboard-rate]
command = xset r rate 200 100

# CMake
[cmake-generate-debug]
command = cmake -DCMAKE_BUILD_TYPE=Debug -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S ./ -B ./cmake-build-debug

[cmake-build-debug]
command = mkdir -p build && cmake -B build && cmake --build build -j

[cmake-build-debug-target]
command = mkdir -p cmake-build-debug cmake --build ./cmake-build-debug --target $(?target) -- -j


# QEMU
[qemu-start-kernel]
command = qemu-system-x86_64 -serial mon:stdio -kernel build/bzImage -initrd build/initramfs.cpio.gz -machine accel=kvm:tcg -append "console=ttyS0 quiet rdinit=$(INIT)"

[qemu-start-kernel-debug]
command = qemu-system-x86_64 -serial mon:stdio -kernel build/bzImage -initrd build/initramfs.cpio.gz -machine accel=kvm:tcg -append "console=ttyS0 quiet rdinit=$(INIT)" -s -S
